### ISSUE TITLE
Failed to push at Openshift

### ISSUE THREAD

**Issue by solankin23** [Tollefsen/angular2-express-seed#1]
[Openshift.txt](https://github.com/Tollefsen/angular2-express-seed/files/414576/Openshift.txt)

**Comment by Tollefsen** [comment]
Error: EACCES, permission denied '/var/lib/openshift/

Do you have writing access to the folder? Anyway, I would recommend using another seed since this seed is for an older version of Angular 2. Currently I have no plans on updating the seed, but I can update the description so nobody else uses the seed.

**Comment by Tollefsen** [comment]
If anyone want to keep the seed up to date, feel free to send a pull request.

**Comment by solankin23** [comment]
thanks for your replay
